(cl:defpackage mscl_msgs-msg
  (:use )
  (:export
   "<FILTERHEADING>"
   "FILTERHEADING"
   "<FILTERHEADINGSTATE>"
   "FILTERHEADINGSTATE"
   "<FILTERSTATUS>"
   "FILTERSTATUS"
   "<GPSCORRELATIONTIMESTAMP>"
   "GPSCORRELATIONTIMESTAMP"
   "<GPSCORRELATIONTIMESTAMPSTAMPED>"
   "GPSCORRELATIONTIMESTAMPSTAMPED"
   "<RTKSTATUS>"
   "RTKSTATUS"
   "<STATUS>"
   "STATUS"
  ))

